### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/collinearity_tool#1]
- [x] Team work contract
- [x] Pick a topic
- [x] Create project structure for the Python project
- [x] Function specifications
- [x] Manage issues
- [x] Check specific expectations

**Comment by showcy** [comment]
All tasks are finished. Submitted.
